pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                dir("backend-service"){
                    sh "./mvnw package"
                }
            }
        }
        stage('Docker Build'){
            steps{
                dir("backend-service"){
                    sh "docker build -t nagabhushanamn/backend-service:latest ."
                }
            }
        }
    }
}