pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                dir("backend-service"){
                    sh "./mvnw package"
                }
            }
        }
        stage('Docker Build'){
            steps{
                dir("backend-service"){
                    sh "docker build -t nagabhushanamn/backend-service:latest ."
                }
            }
        }
        stage('Docker Push'){
            steps{
                dir("backend-service"){
                    sh "docker push nagabhushanamn/backend-service:latest"
                }
            }
        }
         stage('Kubernetes Deploy'){
            steps{
                dir("backend-service"){
                    sh "kubectl apply -f backend-service-deployment.yml"
                    sh "kubectl apply -f backend-service-service.yml"
                }
            }
        }
    }
}