apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service-container
          image: nagabhushanamn/backend-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080

